### ISSUE TITLE
Definining Android SDK number?

### ISSUE THREAD

**Issue by trumpets** [game-ci/unity-actions#106]
This might be something obvious that I am missing, but how do we control which Android SDK we have in the images?

I am using this action:

```
- name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: 2019.4.1f1
          targetPlatform: Android
```

The target SDK is set to 28 (prerequirement of some plugins), so I am getting this error:

```
UnityException: Target Android SDK not installed
Android SDK does not include your Target SDK of 28.
Please use the Android SDK Manager to install your target SDK version. Restart Unity after SDK installation for the changes to take effect.
```

I see that the docker command sends this param: `ANDROID_VERSION_CODE=276`

How do I overwrite this to 280 I'm guessing?

Thanks!
