### ISSUE TITLE
Execute Unity executable directly?

### ISSUE THREAD

**Issue by jcs090218** [game-ci/unity-actions#120]
Quick question here.

Is there a way so we can execute `Unity` executable directly? Something like the following,

```
- name: Execute Unity executable
  run: Unity --batchmode -quite ...
```

Any help will be appreciate it!

**Comment by GabLeRoux** [comment]
**What is your use case for that?**

Technically speaking, unity actions is basically a wrapper for the `unity-editor` command line inside the [docker images](https://game.ci/docs/docker/docker-images). You could probably just identify which docker image is being used and run an action that will execute a shell command in the context of the same docker image.

Here's some draft doing it:

```yaml
jobs:
  container:
    runs-on: ubuntu-latest
    container: unityci/editor:ubuntu-2021.1.21f1-android-0.15.0
    steps:
      - run: |
          find / -name unity
        name: run the find command in the unityci/editor container to find unity executables
```

**Comment by jcs090218** [comment]
> What is your use case for that?

I am trying to call a static method from `Unity` using the flag `-executeMethod`. The command should output a unity package file (`.unitypackage`) or asset bundles, so I can upload them as an artifact.

> Here's some draft doing it:

Cool! Thanks! Would you consider this a feature request so the user would not need to deal with platform arguments, etc? Maybe something similar to...

```yml
jobs:
  task:
    runs-on: ubuntu-latest  # define OS
    steps:
      - uses: game-ci/setup-unity  # Install `Ubuntu` automatically and set up the Unity env path
      - run: Unity -quit -batchmode ...
```

I think this would be helpful if something isn't working properly yet or a workaround. And it's also good for testing purpose?
