### ISSUE TITLE
Directory `build\WebGL\WebGL\Build` gets locked

### ISSUE THREAD

**Issue by jfoshee** [game-ci/unity-actions#131]
**Bug description**

It seems that the build process locks the directory `build\WebGL\WebGL\Build`.
Attempts to write to files in that directory fail immediately following the unity-builder step.

**How to reproduce**

Consider the following excerpt from a YAML action.  The following will pass.  
However if you uncomment the block that runs `unity-builder`, then it will fail at Test Write File 3.

```yaml

      - name: Test Write File 1
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: build/WebGL/WebGL/Build/test.js
          contents: one

      - name: Test Write File 2
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: build/WebGL/WebGL/Build/test.js
          contents: two
          write-mode: append

      # Cache
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
      # Build
#       - name: Build project
#         uses: game-ci/unity-builder@v2
#         env:
#           UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
#           UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
#           UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
#         with:
#           targetPlatform: WebGL

      - name: Test Write File 3
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: build/WebGL/WebGL/Build/test.js
          contents: three
          write-mode: append

      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build
```

**Expected behavior**

The  Action should be able to modify output files as part of the overall build.

**Additional details**

The following error is thrown:

    EACCES: permission denied, open 'build/WebGL/WebGL/Build/test.js'

Interestingly, the parent directories are not locked.  That is, writing to `build/WebGL/WebGL/test.js` is no problem.

See <https://github.com/marketplace/actions/write-file> for info on the write-file Action.

**Comment by jfoshee** [comment]
I discovered this issue was due to the build output files being owned by `root`, while the workflow is being run by user `runner`. This issue was previously filed and discussed here: https://github.com/game-ci/unity-builder/issues/219
And a PR was accepted that allows for a work-around via the `chownFileTo` option: https://github.com/game-ci/unity-builder/pull/250

So, for completeness, I ended up with a work-around like follows:

```yaml
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          targetPlatform: WebGL
          # Instruct build to change owner of build output to the current user (runner)
          # because it defaults to root:root
          # If we don't specify to change the owner we won't be able to modify the files
          chownFilesTo: 1001:1001
```

I know next-to-nothing about Docker.  I identified `1001` as the runner's user ID via the following workflow snippet. 

```yaml
    - run: id
```

If there is a way to improve this I'd love to hear it.  As documented elsewhere it would be great if the runner ended up owning the files by default.
