### ISSUE TITLE
incorrect path for a scene file

### ISSUE THREAD

**Issue by imdonix** [game-ci/unity-actions#140]
**Bug description**

I'm using Unity 2020.3.28f1 on Windows and I'm sure that the game is buildable right now.

And I think the build is failing because of this `'' is an incorrect path for a scene file. BuildPlayer expects paths relative to the project folder.` error.

```
- Starting script compilation
- Starting compile Library/PlayerScriptAssemblies/UnityEngine.TestRunner.dll
- Starting compile Library/PlayerScriptAssemblies/UnityEngine.UI.dll
- Finished compile Library/PlayerScriptAssemblies/UnityEngine.TestRunner.dll in 1.960533 seconds
- Finished compile Library/PlayerScriptAssemblies/UnityEngine.UI.dll in 2.248412 seconds
- Starting compile Library/PlayerScriptAssemblies/Unity.Timeline.dll
- Starting compile Library/PlayerScriptAssemblies/Unity.TextMeshPro.dll
- Finished compile Library/PlayerScriptAssemblies/Unity.Timeline.dll in 1.992778 seconds
- Finished compile Library/PlayerScriptAssemblies/Unity.TextMeshPro.dll in 2.307704 seconds
- Starting compile Library/PlayerScriptAssemblies/Assembly-CSharp.dll
- Finished compile Library/PlayerScriptAssemblies/Assembly-CSharp.dll in 1.359155 seconds
- Finished script compilation in 6.011247 seconds
BuildPlayerGenerator: Succeeded
'' is an incorrect path for a scene file. BuildPlayer expects paths relative to the project folder.
Unloading 0 Unused Serialized files (Serialized files now loaded: 0)
System memory in use before: 63.2 MB.
System memory in use after: 63.3 MB.
```

**Additional details**

- The github workflow:
```
name: Ocean CI

on: [pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2

      # Cache
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows
          customImage: 'unityci/editor:2020.3.27f1-windows-mono-0.17.0'

      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build
```
