### ISSUE TITLE
Error: License is not active (com.unity.editor.headless). HasEntitlements will fail

### ISSUE THREAD

**Issue by megetron** [game-ci/unity-actions#143]
hey and thanks for this wonderful tool!

i am trying to use image `unityci/editor:2020.3.25f1-android-0` to import a unity package with unity-editor:

```yaml
env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE_5 }}
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

jobs:
  set-matrix:
    container: unityci/editor:2020.3.25f1-android-0
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Import SDK
        run: |
          FILE_PATH=UnityLicenseFile.ulf
          echo "${{ secrets.UNITY_LICENSE_5 }}" | tr -d '\r' > $FILE_PATH
          unity-editor -logFile /dev/stdout -quit -manualLicenseFile $FILE_PATH
          unity-editor -quit -logFile Logs/import.log -manualLicenseFile UnityLicenseFile.ulf -projectPath . -ignoreCompilerErrors -importPackage sdk-latest.unitypackage
```

but for some reason i keep getting a unity license activation error. i have double check the activation code and generate a new one just to be sure it was not expired. still this annoying error shown:

```
Unity Editor version:    2020.3.25f1 (9b9[18](https://github.com/Team/sdk.interface.unity/runs/5848368086?check_suite_focus=true#step:11:18)0224418)
Branch:                  2020.3/staging
Build type:              Release
Batch mode:              YES
System name:             Linux
Distro version:          #[19](https://github.com/Team/sdk.interface.unity/runs/5848368086?check_suite_focus=true#step:11:19)~[20](https://github.com/Team/sdk.interface.unity/runs/5848368086?check_suite_focus=true#step:11:20).04.1-Ubuntu SMP Mon Mar 7 11:34:26 UTC 20[22](https://github.com/Team/sdk.interface.unity/runs/5848368086?check_suite_focus=true#step:11:22)
Kernel version:          5.13.0-1017-azure
Architecture:            x86_64
Available memory:        6946 MB
[Licensing::Module] Channel doesn't exist: "LicenseClient-root"
[Licensing::Module] Successfully launched the LicensingClient (PId: 382)
[SignatureVerifier] Application signature verification not supported on this platform.
[Licensing::Module] Successfully connected to LicensingClient on channel: "LicenseClient-root" (connect: 1.[36](https://github.com/Team/sdk.interface.unity/runs/5848368086?check_suite_focus=true#step:11:36)s, validation: 0.09s, handshake: 0.00s)
[Licensing::Module] Connected to LicensingClient (PId: [38](https://github.com/Team/sdk.interface.unity/runs/5848368086?check_suite_focus=true#step:11:38)2, launch time: 0.00, total connection time: 1.45s)
Entitlement-based licensing initiated
[LicensingClient] Licenses updated successfully
[Licensing::Module] Error: License is not active (com.unity.editor.headless). HasEntitlements will fail.
Pro License: NO
Desktop is 640 x 480 @ 60 Hz
[UnityConnectServicesConfig] config is NOT valid, switching to default
Cancelling DisplayDialog: Failed to activate/update license Missing or bad username or password. Please try again using valid credentials or contact support@unity3d.com
This should not be called in batch mode.
```

what am i doing wrong here?
