### ISSUE TITLE
License activation fail when triggered by PR from outside collaborator

### ISSUE THREAD

**Issue by Elringus** [game-ci/unity-actions#144]
Hi, Thank you for making and maintaining the tool!

It worked flawlessly until I got a PR from an outside collaborator, where Unity activation action failed with `License activation strategy could not be determined` error. Just in case I've double-checked the CI script and re-activated the license, but it didn't help.

Here is the PR from outside collaborator: https://github.com/Elringus/SpriteDicing/pull/22, which fails ([action log](https://github.com/Elringus/SpriteDicing/runs/5889653535))
And here's another by maintainer of the repo: https://github.com/Elringus/SpriteDicing/pull/23, which runs fine ([action log](https://github.com/Elringus/SpriteDicing/runs/5890333407))

Below is the CI script:
<details>

```
name: cover

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  cover:
    name: test and cover
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache Library
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: Run tests and generate Coverage XML report
        uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          unityVersion: 2019.4.35f1
          testMode: editmode
          customParameters: -debugCodeOptimization -enableCodeCoverage -coverageResultsPath ./coverage-results -coverageOptions "useProjectSettings;generateAdditionalMetrics"

      - name: Upload XML report to Codecov
        uses: codecov/codecov-action@v2
        with:
          name: EditMode
          flags: automated
          files: coverage-results/**/*.xml
```
</details>
