### ISSUE TITLE
docker: invalid reference format: repository name must be lowercase.

### ISSUE THREAD

**Issue by stephahn0916** [game-ci/unity-actions#148]
**Bug description**

When using CI/CD sample on my own project, the build failed at docker.exe, exit code 125: repository name must be lowercase.

**How to reproduce**

Using windows only, use this workflow definition:
````yaml
name: Build Deploy SoftwareA

on: [push, pull_request]

jobs:
   buildForWindowsBasedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - .
        unityVersion:
          - 2021.1.17f1
        targetPlatform:
          - StandaloneWindows # Build a Windows 32-bit standalone.
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v2
        with:
          path: ${{ matrix.projectPath }}/Library
          key:
            Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}-${{
            hashFiles(matrix.projectPath) }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}-
            Library-${{ matrix.projectPath }}-
            Library-
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}

      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build
````
Returns error
````shell
docker: invalid reference format: repository name must be lowercase.
See 'docker run --help'
Error: The process 'C:\Program Files\Docker\docker.exe' failed with exit code 125
````
The docker command from the log is
````
C:\Program Files\Docker\docker.exe" run 
--workdir /github/workspace 
--rm 
--env UNITY_EMAIL=*** 
--env "UNITY_PASSWORD=mysecretpassword 
--env UNITY_SERIAL=*** 
--env UNITY_VERSION=2021.1.17f1 
--env PROJECT_PATH=. 
--env BUILD_TARGET=StandaloneWindows64 
--env BUILD_NAME=StandaloneWindows64 
--env BUILD_PATH=build/StandaloneWindows64 
--env BUILD_FILE=StandaloneWindows64.exe 
--env VERSION=0.0.8 
--env ANDROID_VERSION_CODE=8 
--env GITHUB_REF=refs/heads/main 
--env GITHUB_SHA=cea9bf73c9e819917e08498a65200a851afa1262 
--env GITHUB_REPOSITORY=Company/SoftwareA 
--env GITHUB_ACTOR=stephahn0916 
--env GITHUB_WORKFLOW=Deploy" "SoftwareA
--env GITHUB_EVENT_NAME=push 
--env GITHUB_WORKSPACE=/github/workspace 
--env GITHUB_ACTION=__game-ci_unity-builder 
--env GITHUB_EVENT_PATH=D:\a\_temp\_github_workflow\event.json 
--env RUNNER_OS=Windows 
--env RUNNER_TOOL_CACHE=C:\hostedtoolcache\windows 
--env RUNNER_TEMP=D:\a\_temp 
--env RUNNER_WORKSPACE=D:\a\SoftwareA              
--env UNITY_SERIAL=***             
--env GITHUB_WORKSPACE=c:/github/workspace                         
--volume D:\a\SoftwareA\SoftwareA:/github/workspace             
--volume c:/regkeys:c:/regkeys             
--volume C:/Program" Files (x86)/Microsoft Visual Studio:C:/Program Files (x86)/Microsoft Visual "Studio             
--volume C:/Program" Files (x86)/Windows Kits:C:/Program Files (x86)/Windows "Kits             --volume C:/ProgramData/Microsoft/VisualStudio:C:/ProgramData/Microsoft/VisualStudio             --volume D:\a\_actions\game-ci\unity-builder\v2/dist/default-build-script:c:/UnityBuilderAction             
--volume D:\a\_actions\game-ci\unity-builder\v2/dist/platforms/windows:c:/steps             
--volume D:\a\_actions\game-ci\unity-builder\v2/dist/BlankProject:c:/BlankProject             unityci/editor:windows-2021.1.17f1-windows-il2cpp-1             
powershell c:/steps/entrypoint.ps1
````
-

**Expected behavior**

Build successful or a more explicit error message

**Additional details**
