### ISSUE TITLE
UNITY_PASSWORD is readable in the log

### ISSUE THREAD

**Issue by stephahn0916** [game-ci/unity-actions#149]
**Bug description**

In game-ci/unity-builder@v2 when building Unity project, build log display UNITY_PASSWORD in clear, while UNITY_EMAIL and UNITY_SERIAL are both hidden

**How to reproduce**
Use the workflow proposed by the  [documentation](https://game.ci/docs/github/getting-started) and follow the instructions on the documentation page. Look at the logs of github action. UNITY_PASSWORD is in clear in the docker command runned. 

**Expected behavior**

Hidden password

**Additional details**

**Comment by webbertakken** [comment]
Thanks for reporting this @stephahn0916,

Can you confirm that your password in fact comes from secrets? In GitHub Actions secrets are supposed to be hidden automatically.

Would you mind sharing your workflow and a screenshot where this happens in your logs? It will help us narrow down the problem.

**Comment by stephahn0916** [comment]
@webbertakken 
the workflow is:
````yaml
name: Build Deploy SoftwareA

on: [push, pull_request]

jobs:
   buildForWindowsBasedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - .
        unityVersion:
          - 2021.1.17f1
        targetPlatform:
          - StandaloneWindows # Build a Windows 32-bit standalone.
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v2
        with:
          path: ${{ matrix.projectPath }}/Library
          key:
            Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}-${{
            hashFiles(matrix.projectPath) }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}-
            Library-${{ matrix.projectPath }}-
            Library-
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}

      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build
````
Screenshot:
 - in red: the password
 - in green: things that I have to anonymize (mostly project name)
![gameci_actions_failure](https://user-images.githubusercontent.com/76950079/174415254-4539d150-66df-4af7-90e8-f13e5c5b51f0.jpg)
