### ISSUE TITLE
ProjectVersion.txt seen by everyone except unity builder

### ISSUE THREAD

**Issue by vadim0x60** [game-ci/unity-actions#150]
In [my github workflow](https://github.com/vadim0x60/virtu-als-plus/blob/f2510ac1c6daad2daf82ab171ed9f428e6487d6d/.github/workflows/build.yml) jobs that look like this:

```
runs-on: ubuntu-latest
steps:
- uses: game-ci/unity-builder@v2
  with:
    targetPlatform: StandaloneLinux64
- uses: actions/upload-artifact@v2
  with:
    name: full-linux-build
    path: build
    retention-days: 1
```

[fail like this](https://github.com/vadim0x60/virtu-als-plus/runs/7090581461?check_suite_focus=true#step:2:20):

```
Error: Project settings file not found at "ProjectSettings/ProjectVersion.txt". Have you correctly set the projectPath?
```

The file in question is very much there, at the [repository root -> ProjectSettings -> ProjectVersion.txt](https://github.com/vadim0x60/virtu-als-plus/blob/f2510ac1c6daad2daf82ab171ed9f428e6487d6d/ProjectSettings/ProjectVersion.txt) and `projectPath` is not set, so it should default to repository root, if I understand correctly.

**Comment by GabLeRoux** [comment]
I think you're missing the checkout action that is used to expose your project's files to the other actions.

https://github.com/actions/checkout

Have a look at the examples located here:  
https://game.ci/docs/github/getting-started

Most of them start with the following action:

```yaml
# ...
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
# ...
```
