### ISSUE TITLE
Mac application can't be opened on Mac

### ISSUE THREAD

**Issue by SethCram** [game-ci/unity-actions#152]
**Bug description**

Mac application can't be opened on Mac.

**How to reproduce**

1. Create a yaml file to build a Unity project for MacOS
2. Run build job 
3. Build succeeds and artifact is output 
4. Download artifact on a Mac 
5. Unzip artifact and run the application
6. Notice how it says "The application can't be opened"

**Expected behavior**

At step 5, I expect the game to launch without issue, assuming the host's firewall is off or the application is allowed.

**Additional details**

- Downloading the artifact with or without mac firewall up didn't make a difference. 
- I've attempted using a Mac instead of a Linux runner with no change.
- I've also attempted to manually change one of the build's files to get executable permissions, but it doesn't show it's working when the artifact is downloaded and inspected.
  - Believe the error is stemming from MacOS build file not being output with executable permissions
  - Because when that file's permissions are changed for the end user on their mac, the game will run properly assuming the firewall is down or the application is allowed
- My yaml file below
```
name: Build for Mac
      on: 
        # A release, pre-release, or draft of a release is published
        release:
          types: published
        # Manual
        workflow_dispatch: {}

jobs:
  buildForMac:
      name: Build for Mac
      runs-on: macos-latest
      strategy:
        fail-fast: false
        matrix:
          targetPlatform:
            - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
            #- StandaloneWindows # Build a Windows 32-bit standalone.
            #- StandaloneWindows64 # Build a Windows 64-bit standalone.
            #- StandaloneLinux64 # Build a Linux 64-bit standalone.
            #- iOS # Build an iOS player.
            #- Android # Build an Android .apk standalone app.
            #- WebGL # WebGL.
      steps:
        # Checkout
        - name: Checkout repository
          uses: actions/checkout@v2
          with:
            lfs: true

        # Cache
        - name: Cache libraries
          uses: actions/cache@v2
          with:
            path: Library
            key: Library-${{ matrix.targetPlatform }}
            restore-keys: |
              Library-

        # Build
        - name: Build project
          uses: game-ci/unity-builder@v2
          env:
            UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
            UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
            UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          with:
            targetPlatform: ${{ matrix.targetPlatform }}

        # Give exe privileges to mac/linux build 
        - name: Give exe privilege to MacOS/Linux build
          if: |
            ${{ matrix.targetPlatform }} == StandaloneOSX || 
              ${{ matrix.targetPlatform }} == StandaloneLinux64
          run: |
            echo 1. Navigating to build folder
            cd build
            echo 2. Contents of build folder:
            ls 
            echo 3. Navigating to game folder
            cd StandaloneOSX
            echo 4. Contents of game folder:
            ls 
            echo 5. Navigating to App folder
            cd StandaloneOSX.app
            echo 6. Contents of App folder:
            ls
            echo 7. Navigating to Contents folder
            cd Contents
            echo 8. Contents of Contents folder:
            ls
            echo 9. Navigating to MacOS folder
            cd MacOS
            echo 10. Contents of MacOS folder:
            ls
            echo 11. Check to see permissions before change
            sudo ls -l
            echo 12. Running cmd to give exe privileges
            sudo chmod -R 777 Friday\ the\ 13th\ Game
            echo 13. Check to see if permissions changed
            sudo ls -l

        # Output build
        - name: Output build as artifact
          uses: actions/upload-artifact@v2
          with:
            name: Build-${{ matrix.targetPlatform }}
            path: build/${{ matrix.targetPlatform }}
```
 - error message referenced above, shown below
<img width="282" alt="Screen Shot 2022-08-23 at 6 13 07 PM" src="https://user-images.githubusercontent.com/86444777/186295991-4172a8d6-d83e-42cd-bfd5-d2cd235eb0d1.png">
 - I've been able to build and play the Unity game on my mac locally without any trouble.

**Comment by davidmfinol** [comment]
macOS has extra security requirements where apps must be signed in order to be distributed over the internet.
I wrote a guide for it on my blog at https://davidmfinol.com/gameci-4_mac.html, but if you want official Apple docs, refer to https://support.apple.com/en-us/HT202491 and https://developer.apple.com/developer-id/
Closing this issue as this isn't a bug, but feel free to ask questions about code signing here or on our Discord at https://game.ci/discord

**Comment by mastef** [comment]
@davidmfinol for an unsigned app the error would look different. Unsigned apps can be opened with shift+right click -> open

The issue above is due to xattr not having run on the final output.

I run this bash script after a successful build in the builder ( it requires xattr to be installed on the host system ):

```bash
cd StandaloneOSX
if ! type "xattr" > /dev/null; then
  echo "xattr does not exist"
else
  xattr -cr mygame.app
fi

find . -type f -iname "MapFileParser" -exec chmod +x {} \;
find . -type f -iname "*.sh" -exec chmod +x {} \;
find . -type f -iname "usymtool" -exec chmod +x {} \;
find . -type f -iname "lzma" -exec chmod +x {} \;
find . -type f -exec chmod +x {} \;
cd ..
```

**Comment by davidmfinol** [comment]
Thanks for the correction @mastef

**Comment by SethCram** [comment]
@mastef I used the script you offered to make a new yaml file and I'm still running into the same issue. Am I using it properly? 
```
name: Build for Mac

on: 
  # A release, pre-release, or draft of a release is published
  release:
    types: published
  # Manual
  workflow_dispatch: {}

jobs:
  buildForMac:
      name: Build for Mac
      runs-on: macos-latest
      strategy:
        fail-fast: false
        matrix:
          targetPlatform:
            - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
            #- StandaloneWindows # Build a Windows 32-bit standalone.
            #- StandaloneWindows64 # Build a Windows 64-bit standalone.
            #- StandaloneLinux64 # Build a Linux 64-bit standalone.
            #- iOS # Build an iOS player.
            #- Android # Build an Android .apk standalone app.
            #- WebGL # WebGL.
      steps:
        # Checkout
        - name: Checkout repository
          uses: actions/checkout@v2
          with:
            lfs: true

        # Cache
        - name: Cache libraries
          uses: actions/cache@v2
          with:
            path: Library
            key: Library-${{ matrix.targetPlatform }}
            restore-keys: |
              Library-
        # Build
        - name: Build project
          uses: game-ci/unity-builder@v2
          env:
            UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
            UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
            UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          with:
            targetPlatform: ${{ matrix.targetPlatform }}
            
        # Run code ripped from issue
        - name: Code Ripped from Issue
          run: |
            cd build
            cd StandaloneOSX
            if ! type "xattr" > /dev/null; then
              echo "xattr does not exist"
              sudo apt-get update -y
              sudo apt-get install -y xattr
            else
              echo "xattr exists" 
              #xattr -cr StandaloneOSX.app
            fi
            
            xattr -cr StandaloneOSX.app
            find . -type f -iname "MapFileParser" -exec chmod +x {} \;
            find . -type f -iname "*.sh" -exec chmod +x {} \;
            find . -type f -iname "usymtool" -exec chmod +x {} \;
            find . -type f -iname "lzma" -exec chmod +x {} \;
            find . -type f -exec chmod +x {} \;
            cd ..
        # Output build
        - name: Output build as artifact
          uses: actions/upload-artifact@v2
          with:
            name: Build-${{ matrix.targetPlatform }}
            path: build/${{ matrix.targetPlatform }}
```
