### ISSUE TITLE
buildMethod causes an error

### ISSUE THREAD

**Issue by muveso** [game-ci/unity-actions#155]
I want to use buildMethod option to remove splash screens on my game but even if the body of the method is empty, there will be no build output and no errors.

I checked the buildMethod script and also I debugged it for correction to handle. When I add buildMethod: line to my workflow, it doesn't provide any output at all.

workflow code:

```

name: Unity iOS Builder 🎮

on: workflow_dispatch

env:
  UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

  GH_PAT: ${{ secrets.GH_PAT }}
  REPO_NAME: ${{ github.event.repository.name }}

  MATCH_REPOSITORY: ${{ secrets.MATCH_REPOSITORY }}
  MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
  MATCH_DEPLOY_KEY: ${{ secrets.MATCH_DEPLOY_KEY }}

  APPLE_CONNECT_EMAIL: ${{ secrets.APPLE_DEVELOPER_EMAIL }}
  APPLE_DEVELOPER_EMAIL: ${{ secrets.APPLE_DEVELOPER_EMAIL }}
  APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
  FASTLANE_USER: ${{ secrets.APPLE_DEVELOPER_EMAIL }}

  APPSTORE_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
  APPSTORE_KEY_ID: ${{ secrets.APPSTORE_KEY_ID }}
  APPSTORE_P8: ${{ secrets.APPSTORE_P8 }}

  IOS_BUILD_PATH: ${{ format('{0}/build/iOS', github.workspace) }}
  IOS_BUNDLE_ID: ${{ secrets.IOS_BUNDLE_ID }}
  PROJECT_NAME: Github Cloud Test Game

jobs:
  buildForiOSPlatform:
    name: Build for iOS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          lfs: true


      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id


      - name: Restore LFS cache
        uses: actions/cache@v2
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard

      - name: Restore Library cache
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ env.REPO_NAME }}-iOS
          restore-keys: |
            Library-${{ env.REPO_NAME }}-
            Library-

      - uses: game-ci/unity-builder@v2
        id: iOSBuildStep
        with:
          targetPlatform: iOS
          allowDirtyBuild: true
          buildMethod: UnityBuilderAction.Builder.BuildProject

      - uses: actions/upload-artifact@v2
        with:
          name: build-iOS
          path: build/iOS

```

Buider.cs:

```

namespace UnityBuilderAction
 {
     public static class Builder
     {
         public static void BuildProject()
         {
             if (!Application.HasProLicense())
             {
                 Console.WriteLine("Unity is not pro :(");
                 EditorApplication.Exit(101);
             }
             else
             {
             Console.WriteLine("UNITY IS PRO! Deactivating SplashScreen");
             PlayerSettings.SplashScreen.show = false;
             PlayerSettings.SplashScreen.showUnityLogo = false;

             EditorApplication.Exit(0);
         }
 }
     }
 }

```

running OS: **ubuntu-latest**
Target Platform: **iOS**
Unity Version: **2020.3.35f1**
