### ISSUE TITLE
Exit Code 133: "Destruction is not allowed when there are still threads waiting on the semaphore."

### ISSUE THREAD

**Issue by edqx** [game-ci/unity-actions#160]
Hi, I've managed to set up manual activation and it looks like my username, password & license are all corrected, but trying to build my project I get:
![image](https://user-images.githubusercontent.com/60631511/206474283-d46b5eb4-3d73-415d-bae5-45e3dc78d966.png)

Building the project works fine on my Windows machine (64 bit).

Workflow file:
```yml
name: Build project

on: [push]

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64 # Build a Windows 64-bit standalone.

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true

      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-

      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          versioning: Tag
          customParameters: "${{ github.event.inputs.debugMode && '-Development -AllowDebugging' }}"

      - uses: actions/upload-artifact@v2
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
```
