### ISSUE TITLE
How to build for il2cpp

### ISSUE THREAD

**Issue by edqx** [game-ci/unity-actions#161]
I feel like this should be a trivial question for unity-builder, but I'm struggling to build my game with il2cpp.

First I got this:
![image](https://user-images.githubusercontent.com/60631511/206699901-a16e27f2-d1ba-4228-94a1-ec506f849e21.png)

Then I tried to use a docker image that ended in `-il2cpp`, one of the ones here: https://hub.docker.com/r/unityci/editor/tags?page=1&name=windows-il2cpp

That got an issue to do with not being able to be ran on linux architecture:
![image](https://user-images.githubusercontent.com/60631511/206700230-9c574cf4-80ad-4818-9d29-e49c617fc878.png)

... So I moved to use Windows Server for my GitHub actions, where now I get this:
![image](https://user-images.githubusercontent.com/60631511/206700367-9e23c0d3-8f8b-4102-8105-0a9de425f83b.png)

But I think this is a lost cause, since `UNITY_EMAIL`, `UNITY_PASSWORD` and `UNITY_LICENSE` are all set fine in the repository's secrets tab.

I think I'm completely on the wrong track here and missing something really obvious, like a bit of xy problem going on.

Thanks.

**Comment by webbertakken** [comment]
You can only build IL2CPP for that platform that you're on.

- linux-il2cpp image can build Linux builds in IL2CPP mode. This image can be run from any runner that supports docker.
- windows-il2cpp image can build Windows in IL2CPP mode. This image can only be run from a Windows runner.

On windows, licensing works differently. If you pass the documented parameters correctly, you should be able to build a Windows IL2CPP build.

Sound like there's just a small misconfiguration issue that occurred because you switched to a Windows runner and Windows activation works differently. Recommend testing that your variables are indeed passed into the workflow step. If nothing else works, please consult our [troubleshooting](https://game.ci/docs/troubleshooting/common-issues) section.

**Comment by edqx** [comment]
So I should run the manual activation step with a windows runner?

**Comment by MrGadget1024** [comment]
> You can only build IL2CPP for that platform that you're on.

From that I gather that the example given [here in the docs](https://game.ci/docs/github/builder#complete-example) can't actually work at all.

**Comment by davidmfinol** [comment]
@MrGadget1024 That example works only if you are using Mono backend for the desktop platforms.

**Comment by MrGadget1024** [comment]
> @MrGadget1024 That example works only if you are using Mono backend for the desktop platforms.

How would I specify to use mono instead of IL2CPP?  I couldn't find that option.

**Comment by davidmfinol** [comment]
Scripting backend can be set as shown in the Unity docs: https://docs.unity3d.com/Manual/Mono.html

**Comment by MrGadget1024** [comment]
> Scripting backend can be set as shown in the Unity docs: https://docs.unity3d.com/Manual/Mono.html

As I said - it's already set to that in Unity.

**Comment by MrGadget1024** [comment]
> Scripting backend can be set as shown in the Unity docs: https://docs.unity3d.com/Manual/Mono.html

Which project file is unity-builder looking in and what's it looking for to determine which scripting backend to use?

**Comment by davidmfinol** [comment]
> Which project file is unity-builder looking in and what's it looking for to determine which scripting backend to use?

Unity should automatically update the `ProjectSettings/ProjectSettings.asset` file when you edit it in the UI, but you should also be able to manually edit that file and set `scriptingBackend.Standalone` to `0`.

**Comment by MrGadget1024** [comment]
> ... manually edit that file and set `scriptingBackend.Standalone` to `0`.
This is what I needed: upstream repo had 1 and fork didn't have project settings saved (thanks Unity) so didn't push.

Now, with that working, WebGL build shows this and it works:

![image](https://user-images.githubusercontent.com/9826063/212082173-f45f3b77-5d97-4405-8552-1b2c34967901.png)

So that begs the question, why can't that work for other platforms on ubuntu-latest, or is there a ubuntu container we need to use that has IL2CPP installed, or is there a command we can invoke to install IL2CPP?

**Comment by MrGadget1024** [comment]
Ok so I switched back to IL2CPP for scripting backend and pushed, and applied a customImage to the workflow, and this failed for all except StandaloneLinux64.

`Error building player because build target was unsupported`

```yml
name: Unity Builder

on:
  push:
    paths:
      - .github/workflows/UnityBuilder.yml

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneOSX         # Build a macOS standalone (Intel 64-bit).
          - StandaloneWindows     # Build a Windows standalone.
          - StandaloneWindows64   # Build a Windows 64-bit standalone.
          - StandaloneLinux64     # Build a Linux 64-bit standalone.
          - iOS                   # Build an iOS player.
          - Android               # Build an Android .apk standalone app.
          - WebGL                 # WebGL.
        unityVersion:
          - 2019.4.40f1
          #- 2020.3.43f1
          #- 2021.3.16f1
          #- 2022.2.1f1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Unity Builder
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          customImage: unityci/editor:ubuntu-2020.3.43f1-linux-il2cpp-1.0.1
          targetPlatform: ${{ matrix.targetPlatform }}
          unityVersion: ${{ matrix.unityVersion }}

      - name: Archive Build
        uses: actions/upload-artifact@v3
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
```
