### ISSUE TITLE
Error: Failed to run "git rev-list --count dcff77d6fb650a7c581fe576e9dc1822256d13e6".

### ISSUE THREAD

**Issue by ErcinDedeoglu** [game-ci/unity-actions#162]
**Bug description**

When I check out from a repository other than the current GitHub repositories, game-ci/unity-builder@2 gives an error.
<img width="577" alt="x1" src="https://user-images.githubusercontent.com/6512072/210216707-8fcdaeb7-dcbd-416b-8af9-bfd51a89f5fe.png">

**How to reproduce**

```yaml
            steps:                  
            - uses: actions/checkout@v2
              with:
                repository: OtherUser/UnityRepo
                token: ${{ secrets.PAT }}
                fetch-depth: 0
                lfs: true
            - uses: actions/cache@v2
              with:
                  path: Library
                  key: Library-${{ matrix.targetPlatform }}
                  restore-keys: Library-
            - uses: game-ci/unity-builder@v2
              env:
                  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
              with:
                  targetPlatform: ${{ matrix.targetPlatform }}
            - uses: actions/upload-artifact@v2
              with:
                  name: Build-${{ matrix.targetPlatform }}
                  path: build/${{ matrix.targetPlatform }}
```

**Expected behavior**

It should be have same behaviour as local repository of GitHub Action.
