### ISSUE TITLE
unity builder with Il2cpp fails on windows-latest

### ISSUE THREAD

**Issue by SimonMeysman** [game-ci/unity-actions#163]
**Bug description**

My unity project fails to build when selecting the windows-latest or windows-2022 runner in github actions. It does work when selecting windows-2019, Here are the final lines from the log:

```
Status: Downloaded newer image for unityci/editor:windows-2022.1.24f1-windows-il2cpp-1
docker: Error response from daemon: hcsshim::CreateComputeSystem 9914b7d2f840cece5f6c3dfb4d5f4f9d202dc6848749229e952225ff114b2848: The container operating system does not match the host operating system.
Error: The process 'C:\Windows\system32\docker.exe' failed with exit code 125
```

**How to reproduce**

following is the relevant snippet from my github action
```yaml
jobs:
    buildClientWindows: 
      name: Build for Windows
      runs-on: windows-latest #[self-hosted, windows]
      strategy:
        fail-fast: false
      steps:
        - uses: actions/checkout@v3
          with:
            lfs: true
        - uses: actions/cache@v3
          with:
            path: Client/Library
            key: Library-StandaloneWindows64
            restore-keys: Library-
        - uses: game-ci/unity-builder@v2
          env:
            UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          with:
            projectPath: Client
            targetPlatform: StandaloneWindows64
```

**Expected behavior**

I would expect that a windows-2022 image runs fine on a windows-2022 system. I know I can always switch back to windows-2019 but I'm trying to switch to windows-2022 to try and debug an issue where some shaders are compiled incorrectly on github, while they are being correctly compiled on windows 10/11 systems locally. 

Please let me know if I can help by providing more information or if this is the wrong place to ask for help on this.
