### ISSUE TITLE
Unclassified error occured while trying to activate license

### ISSUE THREAD

**Issue by kenorb** [game-ci/unity-actions#165]
**Bug description**

Upon running below build workflow, I've got the error:

```
...
Digest: sha256:3ebefdc2f485cc29165994487ce03ac892abd9f885063ae725d3ed88770a91ee
Status: Downloaded newer image for unityci/editor:ubuntu-2021.3.18f1-linux-il2cpp-1
Changing to "/github/workspace/_activate-license" directory.
/github/workspace/_activate-license /github/workspace
Requesting activation (personal license)
Unclassified error occured while trying to activate license.
Exit code was: 1
Error: The process '/usr/bin/docker' failed with exit code 1
```

Build job: https://github.com/Ecilos/ecilos-unity-assets-avatars-sandbox/actions/runs/4184384519/jobs/7249961292#step:3:84

How do I debug this error?

**How to reproduce**

My workflow: https://github.com/Ecilos/ecilos-unity-assets-avatars-sandbox/blob/dev/.github/workflows/build.yml

```
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Unity
        uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: .
          githubToken: ${{ secrets.GITHUB_TOKEN }}
```

**Expected behavior**

Should build the project.

**Additional details**

- I've followed steps from: https://game.ci/docs/github/test-runner
- My UNITY_LICENSE should be correct (type: personal).
- Related: GH-55
