### ISSUE TITLE
Error: The process '/usr/bin/docker' failed with exit code 103

### ISSUE THREAD

**Issue by geeklingo** [game-ci/unity-actions#166]
Migrating from GitLab Runners to GitHub actions. Projects build and deploy fine on GitLab using Game-CI scripts. But on GitHub, iOS and Android build fine but WebGL keeps failing with this error.

```
##utp:{"type":"MemoryLeaks","version":2,"phase":"Immediate","time":1677301391546,"processId":92,"allocatedMemory":3865100,"memoryLabels":[{"Default":8639},{"Permanent":16120},{"Thread":1083180},{"Manager":17598},{"VertexData":12},{"Geometry":280},{"Texture":160},{"Shader":68084},{"Material":24},{"GfxDevice":35528},{"Animation":312},{"Audio":3976},{"Physics":289},{"Serialization":672},{"Input":26792},{"JobScheduler":200},{"Mono":40},{"ScriptingNativeRuntime":43520},{"BaseObject":1621428},{"Resource":944},{"Renderer":1936},{"Transform":48},{"File":26174},{"WebCam":24},{"Culling":40},{"Terrain":1025},{"Wind":24},{"String":30446},{"DynamicArray":65235},{"HashMap":75193},{"Utility":8546},{"Curl":3751},{"PoolAlloc":32192},{"AI":40},{"TypeTree":2064},{"ScriptManager":368},{"RuntimeInitializeOnLoadManager":72},{"SpriteAtlas":112},{"GI":3320},{"Unet":16},{"Director":7816},{"WebRequest":720},{"VR":45689},{"SceneManager":640},{"Video":72},{"LazyScriptCache":32},{"NativeArray":12},{"Camera":25},{"Secure":1},{"SerializationCache":624},{"APIUpdating":5872},{"Subsystems":384},{"VirtualTexturing":57560},{"StaticSafetyDebugInfo":327752},{"EditorGui":40},{"EditorUtility":168743},{"VersionControl":4},{"Undo":450},{"AssetDatabase":10586},{"RestService":1518},{"EditorGi":368},{"License":1312},{"UnityConnect":29664},{"Collab":785},{"Upm":1504},{"DrivenProperties":80},{"HubClient":32},{"LocalIPC":99},{"ProfilerEditor":20133},{"CoreBusinessMetrics":2703},{"Licensing":1424},{"AssetReference":32}]}
Build failed, with exit code 103

###########################
#       Build output      #
###########################

total 8.0K
drwxr-xr-x 2 root root 4.0K Feb 25 05:02 .
drwxr-xr-x 3 root root 4.0K Feb 25 05:02 ..
Changing to "/github/workspace/_activate-license~" directory.
/github/workspace/_activate-license~ /github/workspace
/github/workspace

###########################
#         Failure         #
###########################

Please note that the exit code is not very descriptive.
Most likely it will not help you solve the issue.

To find the reason for failure: please search for errors in the log above.

Error: The process '/usr/bin/docker' failed with exit code 103
```

My main.yml

```
name: Codepipeline

on: [push, pull_request]

jobs:
  buildAndTestForLinuxBasedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - iOS     # Build an iOS player.
          - Android # Build an Android player.
          - WebGL   # WebGL.
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v2
        with:
          path: ${{ matrix.projectPath }}/Library
          key:
            Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}-${{
            hashFiles(matrix.projectPath) }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}-
            Library-${{ matrix.projectPath }}-
            Library-
      - uses: game-ci/unity-test-runner@v2
        id: testRunner
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test results (all modes)
          path: ${{ steps.testRunner.outputs.artifactsPath }}
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          customParameters: '-myParameter myValue -myBoolean -ThirdParameter andItsValue'
          allowDirtyBuild: true
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build
```
