### ISSUE TITLE
unity-test-runner hangs for +6h for no reason

### ISSUE THREAD

**Issue by kenorb** [game-ci/unity-actions#168]
**Bug description**

This issue happens for no reason right after cache was created in the previous job.

Job: https://github.com/Ecilos/ecilos-unity-assets-avatars-sandbox/actions/runs/4288574041/workflow

```
      - name: Set up Unity
        uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
```
It hangs without giving much output:

```
###########################
#   Testing in playmode  #
###########################

Error: The operation was canceled.
```

**How to reproduce**

The same happened in at least few different builds, almost each time:

- https://github.com/Ecilos/ecilos-unity-assets-sandbox/actions/runs/4288532708/jobs/7470635266#step:4:141 <- this one is basically a basic project with empty scene, tested manually with Unity, it loads fine
- https://github.com/Ecilos/ecilos-unity-assets-avatars-sandbox/actions/runs/4288574041/jobs/7470726326#step:4:143
- https://github.com/Ecilos/ecilos-unity-assets-avatars-elementals/actions/runs/4288576425/jobs/7470730956#step:4:141

Is there any param to pass to Docker container to provide more debug information?

**Expected behavior**

It should not hang or provide more debug information why it's stuck or on what command.

**Additional details**

```
      - uses: actions/cache@v2
        with:
          key: library
          path: Library
```

```
Cache Size: ~707 MB (741665115 B)
```
Files were created basically for an empty project.
