### ISSUE TITLE
Unable to activate professional license using actions

### ISSUE THREAD

**Issue by eoleedi** [game-ci/unity-actions#170]
**Bug description**
The logs file says "Cancelling DisplayDialog: Failed to activate/update license Timeout occured while trying to update license. Please try again later or contact support@unity3d.com"
However, the issue is not resolved after trying a couple of times and waiting a couple of days.
I can't find the problem so I come here for help... Any idea would be nice. Thank you!!!
**How to reproduce**
Build a simple unity project and run the Github workflow

```
name: Actions 😎

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    steps:
      # Checkout (without LFS)
      - name: Checkout repository
        uses: actions/checkout@v2

      # Git LFS
      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v2
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard

      # Cache
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Test
      - uses: game-ci/unity-test-runner@v2
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          projectPath: ""
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          targetPlatform: WebGL

      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build
```

**Expected behavior**
Successfully activate and build the project.

**Additional details**
I accidentally follow the steps on GameCI's activation sections for the personal license, whereas I manually request a manual license for a professional license. I have contacted unity to remove the manual license but the problem still exists.
### Logs of unity-test-runner below
```
/usr/bin/docker run --workdir /github/workspace --cidfile /home/runner/work/_temp/container___game-ci_unity-test-runner --rm --env UNITY_LICENSE --env UNITY_LICENSE_FILE --env UNITY_EMAIL --env UNITY_PASSWORD --env UNITY_SERIAL --env UNITY_LICENSING_SERVER= --env UNITY_VERSION=2020.1.17f1 --env PROJECT_PATH=. --env CUSTOM_PARAMETERS= --env TEST_PLATFORMS=playmode;editmode;COMBINE_RESULTS --env COVERAGE_OPTIONS=generateAdditionalMetrics;generateHtmlReport;generateBadgeReport;dontClear --env COVERAGE_RESULTS_PATH=CodeCoverage --env ARTIFACTS_PATH=artifacts --env GITHUB_REF --env GITHUB_SHA --env GITHUB_REPOSITORY --env GITHUB_ACTOR --env GITHUB_WORKFLOW --env GITHUB_HEAD_REF --env GITHUB_BASE_REF --env GITHUB_EVENT_NAME --env GITHUB_WORKSPACE=/github/workspace --env GITHUB_ACTION --env GITHUB_EVENT_PATH --env RUNNER_OS --env RUNNER_TOOL_CACHE --env RUNNER_TEMP --env RUNNER_WORKSPACE --env GIT_PRIVATE_TOKEN= --env CHOWN_FILES_TO= --volume /home/runner/work/_temp/_github_home:/root:z --volume /home/runner/work/_temp/_github_workflow:/github/workflow:z --volume /home/runner/work/gameci-test/gameci-test:/github/workspace:z --volume /home/runner/work/_actions/game-ci/unity-test-runner/v2/dist/steps:/steps:z --volume /home/runner/work/_actions/game-ci/unity-test-runner/v2/dist/entrypoint.sh:/entrypoint.sh:z --volume /home/runner/work/_actions/game-ci/unity-test-runner/v2/dist/unity-config:/usr/share/unity3d/config/:z --env USE_EXIT_CODE=false unityci/editor:ubuntu-2020.1.17f1-linux-il2cpp-1 /bin/bash -c /entrypoint.sh
Unable to find image 'unityci/editor:ubuntu-2020.1.17f1-linux-il2cpp-1' locally
ubuntu-2020.1.17f1-linux-il2cpp-1: Pulling from unityci/editor
08a6abff8943: Pulling fs layer
17bc3eeef474: Pulling fs layer
7525af58113d: Pulling fs layer
643424925c07: Pulling fs layer
a64283161285: Pulling fs layer
6f8bb29b92de: Pulling fs layer
643424925c07: Waiting
a64283161285: Waiting
6f8bb29b92de: Waiting
f93bd952912f: Pulling fs layer
fe57e0ee0755: Pulling fs layer
2e362b557262: Pulling fs layer
0361e49d8d85: Pulling fs layer
4f4fb700ef54: Pulling fs layer
f93bd952912f: Waiting
fe57e0ee0755: Waiting
2e362b557262: Waiting
0361e49d8d85: Waiting
4f4fb700ef54: Waiting
a1f2b96f5fb8: Pulling fs layer
a1f2b96f5fb8: Waiting
17bc3eeef474: Verifying Checksum
17bc3eeef474: Download complete
08a6abff8943: Verifying Checksum
08a6abff8943: Download complete
643424925c07: Verifying Checksum
643424925c07: Download complete
a64283161285: Verifying Checksum
a64283161285: Download complete
6f8bb29b92de: Verifying Checksum
6f8bb29b92de: Download complete
f93bd952912f: Verifying Checksum
f93bd952912f: Download complete
7525af58113d: Verifying Checksum
7525af58113d: Download complete
2e362b557262: Verifying Checksum
2e362b557262: Download complete
4f4fb700ef54: Verifying Checksum
4f4fb700ef54: Download complete
0361e49d8d85: Verifying Checksum
0361e49d8d85: Download complete
08a6abff8943: Pull complete
a1f2b96f5fb8: Verifying Checksum
a1f2b96f5fb8: Download complete
17bc3eeef474: Pull complete
7525af58113d: Pull complete
643424925c07: Pull complete
a64283161285: Pull complete
6f8bb29b92de: Pull complete
f93bd952912f: Pull complete
fe57e0ee0755: Download complete
fe57e0ee0755: Pull complete
2e362b557262: Pull complete
0361e49d8d85: Pull complete
4f4fb700ef54: Pull complete
a1f2b96f5fb8: Pull complete
Digest: sha256:3ddf363cdad5390cfe2a2764d85834f5a790c73eeb043e954cdd6af88e3e89eb
Status: Downloaded newer image for unityci/editor:ubuntu-2020.1.17f1-linux-il2cpp-1
Changing to "/github/workspace/_activate-license" directory.
/github/workspace/_activate-license /github/workspace
Requesting activation (professional license)
[Licensing::Module] Channel doesn't exist: "LicenseClient-root"
[Licensing::Module] Successfully launched the LicensingClient (PId: 30)
[SignatureVerifier] Application signature verification not supported on this platform.
[Licensing::Module] Successfully connected to LicensingClient on channel: "LicenseClient-root" (connect: 0.83s, validation: 0.06s, handshake: 0.00s)
[Licensing::Module] Connected to LicensingClient (PId: 30, launch time: 0.00, total connection time: 0.90s)
Entitlement-based licensing initiated
[LicensingClient] Licenses updated successfully
DisplayProgressbar: Unity license
[UnityConnectServicesConfig] config is NOT valid, switching to default
User *** logged in successfully

LICENSE SYSTEM [2023323 21:20:32] Starting license activation with account ***


LICENSE SYSTEM [2023323 21:20:32] Opening https://license.unity3d.com/update/poll?cmd=9&tx_id=b2e2c717cdfc6f0ad9befde2fbd4071a&(serial removed)

LICENSE SYSTEM [2023323 21:20:32] Posting <?xml version="1.0" encoding="UTF-8"?><root><SystemInfo><IsoCode>C.UTF</IsoCode><UserName>(unset)</UserName><OperatingSystem>Linux 5.[15](https://github.com/eoleedi/gameci-test/actions/runs/4505314022/jobs/7930878649#step:7:16) Ubuntu 18.04 64bit</OperatingSystem><OperatingSystemNumeric>515</OperatingSystemNumeric><ProcessorType>Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz</ProcessorType><ProcessorSpeed>2593</ProcessorSpeed><ProcessorCount>2</ProcessorCount><ProcessorCores>2</ProcessorCores><PhysicalMemoryMB>6943</PhysicalMemoryMB><ComputerName>9bf7dca34c36</ComputerName><ComputerModel>PC</ComputerModel><UnityVersion>2020.1.17f1</UnityVersion><SupportedLicenseVersion>6.x</SupportedLicenseVersion></SystemInfo><License id="Terms"><MachineID Value="D7nTUnjNAmtsUMcnoyrqkgIbYdM=" /><MachineBindings><Binding Key="1" Value="57656262657226476[16](https://github.com/eoleedi/gameci-test/actions/runs/4505314022/jobs/7930878649#step:7:17)24c65526f7578" /><Binding Key="2" Value="576562626572264761624c65526f7578" /></MachineBindings><UnityVersion Value="2020.1.[17](https://github.com/eoleedi/gameci-test/actions/runs/4505314022/jobs/7930878649#step:7:18)f1" /></License></root>


LICENSE SYSTEM [[20](https://github.com/eoleedi/gameci-test/actions/runs/4505314022/jobs/7930878649#step:7:21)23323 [21](https://github.com/eoleedi/gameci-test/actions/runs/4505314022/jobs/7930878649#step:7:22):20:35] Received https://license.unity3d.com/update/poll?cmd=9&tx_id=b2e2c717cdfc6f0ad9befde2fbd4071a&(serial removed)

LICENSE SYSTEM [2023323 21:20:35] Headers:
    HTTP/1.1 200 OK
    x-rx: GEN-ca5a9041-7[22](https://github.com/eoleedi/gameci-test/actions/runs/4505314022/jobs/7930878649#step:7:23)0-4dd1-9c4c-1ecc55[25](https://github.com/eoleedi/gameci-test/actions/runs/4505314022/jobs/7930878649#step:7:26)5f0e
    vary: Accept-Encoding
    vary: Accept-Encoding
    sc-token-expires-in: 7225
    cache-control: no-cache, no-store, must-revalidate
    pragma: no-cache
    expires: 0
    Content-Encoding: deflate
    sc-request-id: 06f2cb1c-a569-4ba3-bc2f-53d3af7a65ce
    Content-Type: text/plain
    Transfer-Encoding: chunked
    

Cancelling DisplayDialog: Failed to activate/update license Timeout occured while trying to update license. Please try again later or contact support@unity3d.com
This should not be called in batch mode. 
(Filename: ./Editor/Platform/Linux/EditorUtility.cpp Line: [27](https://github.com/eoleedi/gameci-test/actions/runs/4505314022/jobs/7930878649#step:7:28)4)

Unclassified error occured while trying to activate license.
Exit code was: 1
Error: The process '/usr/bin/docker' failed with exit code 1
```
