### ISSUE TITLE
windows-2019 CPP2ILL build sometimes times out while finishing personal license check

### ISSUE THREAD

**Issue by SimonMeysman** [game-ci/unity-actions#173]
**Bug description**

About 2/3s of my cron triggered full build runs fail. Annoyingly, this means that I cannot give clear steps to reproduce it. More correctly, they don't fail but time out after the allotted 6h github allows for actions to run. Most of these failed runs show that the build was successful and that the license was correctly checked. example of such run: 
```
Directory: C:\github\workspace\build\StandaloneWindows64


Mode                LastWriteTime         Length Name                          
----                -------------         ------ ----                          
d-----        5/***9/2023  ***0:38 PM                my-project_BackUpThisFolder_ButDont
                                                 ShipItWithYourGame            
d-----        5/***9/2023  ***0:37 PM                my-project_Data                    
-a----        5/***9/2023  ***0:*** PM         4***8840 baselib.dll                   
-a----        5/***9/2023  ***0:38 PM       837***2000 GameAssembly.dll              
-a----        5/***9/2023  ***0:*** PM         666624 my-project.exe                     
-a----        5/***9/2023  ***0:*** PM        ***5***60 UnityCrashHandler64.exe       
-a----        5/***9/2023  ***0:*** PM       3029***992 UnityPlayer.dll               

User *** logged in successfully
[Licensing::Module] Trying to connect to existing licensing client channel...
[Licensing::IpcConnector] Connection attempt to the License Client on channel: "LicenseClient-ContainerAdministrator" failed because channel doesn't exist; code: "0x80000002"
[Licensing::Module] Successfully launched the LicensingClient (PId: 6520)
[Licensing::IpcConnector] Successfully connected to the License Client on channel: "LicenseClient-ContainerAdministrator"
[Licensing::Client] Handshaking with LicensingClient:
  Version:                 ***.***2.0+3acf7bc
  Session Id:              2ff44c3b39ff47b***8***5dcdbd2f***099cc
  Correlation Id:          9cdb***c5208305d3388d659af5d8ffe68
  External correlation Id: 6449983800***77***4650
  Machine Id:              KzswfZcGfJVxNX/zbCmkn2HOMQY=
[Licensing::Module] Successfully connected to LicensingClient on channel: "LicenseClient-ContainerAdministrator" (connect: ***.63s, validation: 0.***0s, handshake: 2.42s)
[Licensing::IpcConnector] Successfully connected to the License Notification on channel: "LicenseClient-ContainerAdministrator-notifications"
[Licensing::Module] Connected to LicensingClient (PId: 6520, launch time: 0.0***, total connection time: 4.***4s)
[Licensing::Client] Successfully updated the access token
[Licensing::Module] Successfully updated the access token -FQDWYAkOv...
[Licensing::Client] Successfully processed license management request
[Licensing::Module] Successfully returned the entitlement license
[Licensing::Client] Successfully queried for the EntitlementGroupsDetails
[Licensing::Client] Successfully returned ULF license with serial number : "F4-RJWW-BKXG-EFFX-HGS3-XXXX"
Error: The operation was canceled.
```

Other times, the activation of the license did not work, and this message gets printed in the logs directly after the repo checkout has finished. Sadly, this failed activation check does not cause the action to fail, simply to time out after 6 hours. example:
```
 Status: Downloaded newer image for unityci/editor:windows-2022.2.***2f***-windows-il2cpp-***
Request timed out while processing request "https://core.cloud.unity3d.com/api/login", HTTP error code 0
.[UnityConnect] Request timed out.
[Licensing::Module] Trying to connect to existing licensing client channel...
[Licensing::IpcConnector] Connection attempt to the License Client on channel: "LicenseClient-ContainerAdministrator" failed because channel doesn't exist; code: "0x80000002"
[Licensing::Module] Successfully launched the LicensingClient (PId: 5372)
[Licensing::IpcConnector] Successfully connected to the License Client on channel: "LicenseClient-ContainerAdministrator"
[Licensing::Client] Handshaking with LicensingClient:
  Version:                 ***.***2.0+3acf7bc
  Session Id:              fac4b29f88e84d9b9c6e9***d8bab7af
  Correlation Id:          6745728c37ae73f866aa5***fc6728593f
  External correlation Id: 7397039533***0877895***
  Machine Id:              EdJZkmgKinZPz4u0lfl3SzlPaew=
[Licensing::Module] Successfully connected to LicensingClient on channel: "LicenseClient-ContainerAdministrator" (connect: 2.9***s, validation: 0.05s, handshake: 2.65s)
[Licensing::IpcConnector] Successfully connected to the License Notification on channel: "LicenseClient-ContainerAdministrator-notifications"
[Licensing::Module] Connected to LicensingClient (PId: 5372, launch time: 0.02, total connection time: 5.6***s)
[Licensing::Module] Error: Access token is unavailable; failed to update
[Licensing::Module] Error: Failed to activate entitlement license
[Licensing::Module] Error: Access token is unavailable; failed to update
[Licensing::Module] Error: Failed to activate ULF license
Error: The operation was canceled.
```

If it helps, here is my build action:
```yaml
  build-client-windows:
    name: Build my-project for Windows
    runs-on: windows-2019
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
          fetch-depth: 1
      - uses: actions/cache@v3
        with:
          path: Client/Library
          key: Library-StandaloneWindows64-${{ secrets.CACHE_VERSION }}
      - name: copy settings file to use non-developer build settings
        id: overwrite_project-settings
        run: Copy-Item -Path Client/ProjectSettings/ProjectSettings-release.asset -Destination Client/ProjectSettings/ProjectSettings.asset -Force
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: Client
          targetPlatform: StandaloneWindows64
          allowDirtyBuild: true
          buildName: my-project
```

This action always runs on github-hosted machines. Some of the time, it does work. I have no such issues with the license activation when creating webgl builds for the same codebase. I am unable to use windows-latest to build this as docker-images for windows-2022 these are not yet available. A normal build-run takes about 2 hours normally. This issue has been going on for almost a month now. 

**Expected behaviour**
Obviously I would hope that my build would always succeed. However, if something fails during the initial activation of the license, I would hope that the activation ,could maybe be tried again (as it might be an issue with the unity license servers) and if multiple activation attempts fail, I would expect the action to fail in stead of simply timing out. 
As for the runs where the build and license are successfully activated, I would expect them to simply finish correctly. The only difference between those logs and logs of a succeeded build is one extra line at the end of the log, showing it exiting the application.

```  
User *** logged in successfully
[Licensing::Module] Trying to connect to existing licensing client channel...
[Licensing::IpcConnector] Connection attempt to the License Client on channel: "LicenseClient-ContainerAdministrator" failed because channel doesn't exist; code: "0x80000002"
[Licensing::Module] Successfully launched the LicensingClient (PId: 2300)
[Licensing::IpcConnector] Successfully connected to the License Client on channel: "LicenseClient-ContainerAdministrator"
[Licensing::Client] Handshaking with LicensingClient:
  Version:                 ***.***2.0+3acf7bc
  Session Id:              36d76***0535d***4f39a3ac84***8ebfcf7c9
  Correlation Id:          c9a5ea252***4e7896d65422e2377e2fb3
  External correlation Id: 3294957848060326384
  Machine Id:              DJlvi4uEBGRLHCpJbGmMr0zGOGI=
[Licensing::Module] Successfully connected to LicensingClient on channel: "LicenseClient-ContainerAdministrator" (connect: ***.44s, validation: 0.09s, handshake: 2.43s)
[Licensing::IpcConnector] Successfully connected to the License Notification on channel: "LicenseClient-ContainerAdministrator-notifications"
[Licensing::Module] Connected to LicensingClient (PId: 2300, launch time: 0.0***, total connection time: 3.97s)
[Licensing::Client] Successfully updated the access token
[Licensing::Module] Successfully updated the access token 5-ZqtyQoD7...
[Licensing::Client] Successfully processed license management request
[Licensing::Module] Successfully returned the entitlement license
[Licensing::Client] Successfully queried for the EntitlementGroupsDetails
[Licensing::Client] Successfully returned ULF license with serial number : "F4-RJWW-BKXG-EFFX-HGS3-XXXX"
Exiting without the bug reporter. Application will terminate with return code 0
```
