### ISSUE TITLE
Macos runner fails to build

### ISSUE THREAD

**Issue by g0josh** [game-ci/unity-actions#174]
**Bug description**

Building for iOS on `macos-latest` fails with `Error building player because build target was unsupported`. Interestingly it succeeds when running on `ubuntu-latest`. Also noticed running on `macos-latest` does not install `ios` module while installing unity editor. 

```
/Applications/Unity Hub.app/Contents/MacOS/Unity Hub -- --headless install --version 2022.2.19f1 --changeset 765657fe9343 --module mac-il2cpp --childModules
```

Tried setting `customImage` in workflow step to `2022.2.20f1-ios-1.1.2`, which did not make any difference. 

**How to reproduce**
Using Unity editor version `2022.2.19f1` 

```
      - name: Build
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE_MAC }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL_MAC }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD_MAC }}
        with:
          targetPlatform: iOS
          projectPath: flutter/unity/TestAddressables
```
-

**Expected behavior**

Unity build to succeed in `macos-latest`. 

**Additional details**

[3_Build.txt](https://github.com/game-ci/unity-actions/files/11591116/3_Build.txt)
