### ISSUE TITLE
Can't use androidExportType with game-ci/unity-builder@v2

### ISSUE THREAD

**Issue by SethCram** [game-ci/unity-actions#177]
**Bug description**
When attempting to create an Android build on a Linux runner, I keep receiving the following warning despite how the docs recommends using androidExportType instead of androidAppBundle.

```
Warning: Unexpected input(s) 'androidExportType', valid inputs are ['targetPlatform', 
'unityVersion', 'customImage', 'projectPath', 'buildName', 'buildsPath', 'buildMethod', 
'customParameters', 'versioning', 'version', 'androidVersionCode', 'androidAppBundle', 
'androidKeystoreName', 'androidKeystoreBase64', 'androidKeystorePass', 
'androidKeyaliasName', 'androidKeyaliasPass', 'androidTargetSdkVersion', 'sshAgent',
 'gitPrivateToken', 'chownFilesTo', 'allowDirtyBuild', 'postBuildSteps', 'preBuildSteps', 
'customJobHooks', 'customJob', 'awsBaseStackName', 'cloudRunnerCluster', 
'cloudRunnerCpu', 'cloudRunnerMemory', 'cachePushOverrideCommand', 
'cachePullOverrideCommand', 'readInputFromOverrideList', 
'readInputOverrideCommand', 'kubeConfig', 'kubeVolume', 'kubeStorageClass', 
'kubeVolumeSize', 'cacheKey', 'checkDependencyHealthOverride', 
'startDependenciesOverride']
```

My Yaml file: 
```
name: Build for Android

on: 
  # Manual 
  workflow_dispatch: {}

jobs:
  build:
    name: Build my project 
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Cache
      - name: Cache libraries
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: Android
          #build an android studio project 
          androidExportType: 'androidStudioProject'
      
      # Output build
      - name: Output build
        uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build

```
