### ISSUE TITLE
Error: The process '/usr/bin/docker' failed with exit code 101 w/ v3.1.0

### ISSUE THREAD

**Issue by RajSriShanker** [game-ci/unity-actions#179]
For some reason I keep running into issues, however I was able to get this running on earlier projects without a issue. I am now running into the error code "Error: The process '/usr/bin/docker' failed with exit code 101". I have attached logs of the error.

[7_Run game-ciunity-builder@v3.1.0.txt](https://github.com/game-ci/unity-actions/files/12852800/7_Run.game-ciunity-builder%40v3.1.0.txt)

I am using game-ci/unity-builder@v3.1.0 and made sure the .gitignore is correct. My workflow is the following:

```
name: GameCI Template 🎮

on: push

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  buildWebGL:
    name: Build for WebGL 🖥️
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v2
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard

      - name: Restore Library cache
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-build-WebGL
          restore-keys: |
            Library-build-
            Library-

      - uses: game-ci/unity-builder@v3.1.0
        with:
          targetPlatform: WebGL

      - uses: actions/upload-artifact@v2
        with:
          name: build-WebGL
          path: build/WebGL


  deployPages:
    needs: buildWebGL
    name: Deploy to Github Pages 🚀
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: build-WebGL
          path: build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: build/WebGL
```
