### ISSUE TITLE
Issue when trying to use Builder

### ISSUE THREAD

**Issue by Roxeez** [game-ci/unity-actions#185]
Hello,
I'm trying to build my game from GitHub actions and i'm getting this error everytime
```
###########################
#         Failure         #
###########################

Please note that the exit code is not very descriptive.
Most likely it will not help you solve the issue.

To find the reason for failure: please search for errors in the log above.

Error: The process '/usr/bin/docker' failed with exit code 133
```

And when i scroll up to find an error i that what i found
```
Error: There was an error while trying to activate the Unity license.
Activation complete.
```

Looks like my game is building correctly but there is some problem with the license at some point

Here is my CI yaml file
```
name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        projectPath: [Kitow]
        targetPlatform: [StandaloneWindows64]
          
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Create tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        default_bump: patch
        default_prerelease_bump: patch
        release_branches: main,develop
        pre_release_branches: prerelease
        tag_prefix: ''
        dry_run: true
        
    - name: Loading/Saving cached files
      uses: actions/cache@v2
      with:
        path: ${{ matrix.projectPath }}/Library
        key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
        restore-keys: |
          Library-${{ matrix.projectPath }}-
          Library-
        
    - name: Unity - Build
      uses: game-ci/unity-builder@v4
      env:
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      with:
        projectPath: ${{ matrix.projectPath }}
        targetPlatform: ${{ matrix.targetPlatform }}
        versioning: Custom
        version: ${{ steps.tag_version.outputs.new_tag }}
```

I've followed steps described in documentation :

- copy content of file in C:\ProgramData\Unity into UNITY_LICENSE secret)
- add email to secrets
- add password to secrets
