### ISSUE TITLE
Unity error resolving packages in the activate license step

### ISSUE THREAD

**Issue by txema-martinez-scopely** [game-ci/unity-actions#97]
**Bug description**

I use the test-runner action configured as:
```
      - uses: game-ci/unity-test-runner@v1.7
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          projectPath: CoreService.Client.Services.Unity
          unityVersion: 2018.4.9f1
```

The Unity command in `activate.sh` throws the following error:
```
An error occurred while resolving packages:
  Package com.scopely.coreservice.client.analytics@file:/github/workspace/Packages/CoreService.Client.Analytics.Package has invalid dependencies:
    com.scopely.sdk.core: Package [com.scopely.sdk.core@1.2.7] cannot be found
  Package com.scopely.coreservice.clientservices@file:/github/workspace/Packages/CoreService.Client.Services.Package has invalid dependencies:
    com.scopely.coreservice.common: Package [com.scopely.coreservice.common@1.0.131] cannot be found
  Package com.scopely.coreservice.clientservices.assetbundlepublisher@file:/github/workspace/Packages/CoreService.Client.Services.AssetBundlePublisher.Package has invalid dependencies:
    com.scopely.jsondotnet: Package [com.scopely.jsondotnet@0.0.2] cannot be found
```

**How to reproduce**

Configure a test-runner action with `projectPath` argument.

**Expected behavior**

The license activation step should run without errors.

**Additional details**

I tried to run the same command in my local machine and I get the same error:
```
/Applications/Unity/Hub/Editor/2018.4.9f1/Unity.app/Contents/MacOS/Unity -batchmode -nographics -logFile /dev/stdout -quit -serial SC-****-****-****-****-**** -username ******** -password ******** $HOME/tmp/workspace
```

I need to add the `projectPath` argument to make it work:
```
/Applications/Unity/Hub/Editor/2018.4.9f1/Unity.app/Contents/MacOS/Unity -batchmode -nographics -logFile /dev/stdout -quit -serial SC-****-****-****-****-**** -username ******** -password ******** -projectPath $HOME/tmp/workspace/CoreService.Client.Services.Unity $HOME/tmp/workspace
```

**Comment by txema-martinez-scopely** [comment]
Also reproduced in the last `unity-test-runner` version

**Comment by webbertakken** [comment]
A few things to try:

- Could you try quoting the project path? 
- Does the specified `unityVersion` match your projects Unity version?
- Is the root of your project inside that folder and is that folder in the root of your repository?

The problem must be more specific than `projectPath` being broken, as it works with project path in this test-runner repos own workflow and for other projects.

**Comment by txema-martinez-scopely** [comment]
> Could you try quoting the project path?

I just tried it. Same error in package resolution


> Does the specified unityVersion match your projects Unity version?

Yes, my project's Unity version is `2018.4.9f1`.


> Is the root of your project inside that folder and is that folder in the root of your repository?

In the root of my repo I have 2 directories:
- Packages: containing several Unity packages source code
- CoreService.Client.Services.Unity: containing the Unity project that references the previous packages


> The problem may also be that these packages indeed can not be resolved from the container.

I just embedded the `unity-test-runner` repo content in my repo's `.github/actions/unity-test-runner` directory, applied the fix in PR game-ci/unity-test-runner#107 and the packages were resolved correctly and the tests were run without problems using this configuration:
```
      - uses: ./.github/actions/unity-test-runner/
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          projectPath: WithBuddies.Client.Services.Unity
          unityVersion: 2018.4.9f1
```
