### ISSUE TITLE
Using private repository with manifest.json not work

### ISSUE THREAD

**Issue by BijanJab** [game-ci/unity-actions#99]
**Bug description**

If I add a private repository as a package in packages/manifest.json
```
{
  "dependencies": {
    "my_repo": "someprivaterepo.git",
  //...
} 
```
it fails with this error  :
```
when executing the git command. fatal: could not read Username for 'https://github.com': terminal prompts disabled
You may need to set up a Git credentials helper to access a private repository.
```
I tried using git credential package helper : 
```
- uses: oleksiyrudenko/gha-git-credentials@v2-latest
   with:
      global: true
      name: ...
      email: ...
      actor: ...
      token: ...
```
But I still get the same error, I think the reason is that local git credentials are not exported to unity builder docker .
I'm stuck at this, How can I solve this problem?
